# NFL Contracts from Spotrac — ~2,800 players with contract data
#
# Source: db/seeds/data/spotrac_contracts.json (generated by bin/rails spotrac:scrape)
# Creates: Person + Athlete + Contract for every NFL roster player

json_path = Rails.root.join("db/seeds/data/spotrac_contracts.json")

if File.exist?(json_path)
  entries = JSON.parse(File.read(json_path), symbolize_names: true)
  created = { people: 0, athletes: 0, contracts: 0 }
  skipped = 0

  entries.each do |data|
    # Normalize position via PositionConcern (Spotrac source vocabulary)
    position = PositionConcern.normalize_position(data[:position], source: :spotrac)

    # Person — smart name matching (handles J.T. vs JT, Cam vs Cameron, etc.)
    person = Person.find_or_create_by_name!(data[:first_name], data[:last_name], athlete: true)
    created[:people] += 1 if person.previously_new_record?

    # Athlete
    athlete = Athlete.find_or_create_by!(person_slug: person.slug) do |a|
      a.sport = "football"
      a.position = position
    end
    created[:athletes] += 1 if athlete.previously_new_record?

    # Contract — expires at end of contract end_year (NFL league year starts mid-March)
    expires_at = data[:end_year] > 0 ? Date.new(data[:end_year], 3, 15) : nil

    contract = Contract.find_or_create_by!(person_slug: person.slug, team_slug: data[:team_slug]) do |c|
      c.annual_value_cents = data[:annual_value_cents]
      c.position = position
      c.contract_type = "active"
      c.expires_at = expires_at
    end
    created[:contracts] += 1 if contract.previously_new_record?
  rescue ActiveRecord::RecordInvalid => e
    skipped += 1
    puts "  SKIP: #{data[:first_name]} #{data[:last_name]} — #{e.message}" if skipped <= 10
  end

  puts "NFL Contracts (Spotrac): #{created[:contracts]} contracts, #{created[:people]} people, #{created[:athletes]} athletes"
  puts "  Skipped: #{skipped}" if skipped > 0
else
  puts "SKIP: #{json_path} not found — run `bin/rails spotrac:scrape` first"
end
